### ISSUE TITLE
std classes

### ISSUE THREAD

**Issue by xakod** [awulkiew/debugging-helpers#3]
Hello, thank you for your helpers. I see you implemented support for boost.tuple and boost.variant2. Is there any chance for std tuple (similar to boost.tuple) and std variant (similar to boost.variant2)?

Found working impl https://github.com/Stat1cV01D/qtc-debugging-helpers

**Comment by awulkiew** [comment]
I don't plan on writing them at the moment.

They should've been provided by QtCreator in this file:
https://github.com/qt-creator/qt-creator/blob/master/share/qtcreator/debugger/stdtypes.py
but they're not.

**Comment by xakod** [comment]
Ok, thank you!
